<a href="https://colab.research.google.com/github/taeyeon02/nlp_lab/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# 1차원 배열
vec = np.array([1, 2, 3, 4, 5])
print(vec)

[1 2 3 4 5]


In [ ]:
# 2차원 배열
mat = np.array([[10, 20, 30], [ 60, 70, 80]]) 
print(mat)

[[10 20 30]
 [60 70 80]]


In [ ]:
print('vec의 타입 :',type(vec))
print('mat의 타입 :',type(mat))

vec의 타입 : <class 'numpy.ndarray'>
mat의 타입 : <class 'numpy.ndarray'>


In [ ]:
print('vec의 축의 개수 :',vec.ndim) # 축의 개수 출력
print('vec의 크기(shape) :',vec.shape) # 크기 출력

vec의 축의 개수 : 1
vec의 크기(shape) : (5,)


In [ ]:
print('mat의 축의 개수 :',mat.ndim) # 축의 개수 출력
print('mat의 크기(shape) :',mat.shape) # 크기 출력

mat의 축의 개수 : 2
mat의 크기(shape) : (2, 3)


In [ ]:
# 모든 값이 0인 2x3 배열 생성.
zero_mat = np.zeros((2,3))
print(zero_mat)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# 모든 값이 1인 2x3 배열 생성.
one_mat = np.ones((2,3))
print(one_mat)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# 모든 값이 특정 상수인 배열 생성. 이 경우 7.
same_value_mat = np.full((2,2), 7)
print(same_value_mat)

[[7 7]
 [7 7]]


In [ ]:
# 대각선 값이 1이고 나머지 값이 0인 2차원 배열을 생성.
eye_mat = np.eye(3)
print(eye_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# 임의의 값으로 채워진 배열 생성
random_mat = np.random.random((2,2)) # 임의의 값으로 채워진 배열 생성
print(random_mat)

[[0.22459045 0.40745937]
 [0.36351053 0.89857723]]


In [ ]:
# 0부터 9까지
range_vec = np.arange(10)
print(range_vec)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# 1부터 9까지 +2씩 적용되는 범위
n = 2
range_n_step_vec = np.arange(1, 10, n)
print(range_n_step_vec)

[1 3 5 7 9]


In [ ]:
reshape_mat = np.array(np.arange(30)).reshape((5,6))
print(reshape_mat)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [ ]:
mat = np.array([[1, 2, 3], [4, 5, 6]])
print(mat)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 첫번째 행 출력
slicing_mat = mat[0, :]
print(slicing_mat)

[1 2 3]


In [ ]:
# 두번째 열 출력
slicing_mat = mat[:, 1]
print(slicing_mat)

[2 5]


In [ ]:
mat = np.array([[1, 2], [4, 5], [7, 8]])
print(mat)

[[1 2]
 [4 5]
 [7 8]]


In [ ]:
# 1행 0열의 원소
# => 0부터 카운트하므로 두번째 행 첫번째 열의 원소.
print(mat[1, 0])

4


In [ ]:
# mat[[2행, 1행],[0열, 1열]]
# 각 행과 열의 쌍을 매칭하면 2행 0열, 1행 1열의 두 개의 원소.
indexing_mat = mat[[2, 1],[0, 1]]
print(indexing_mat)

[7 5]


In [ ]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [ ]:
# result = np.add(x, y)와 동일.
result = x + y
print(result)

[5 7 9]


In [ ]:
# result = np.subtract(x, y)와 동일.
result = x - y
print(result)

[-3 -3 -3]


In [ ]:
# result = np.multiply(result, x)와 동일.
result = result * x
print(result)

[-3 -6 -9]


In [ ]:
# result = np.divide(result, x)와 동일.
result = result / x
print(result)

[-3. -3. -3.]


In [ ]:
mat1 = np.array([[1,2],[3,4]])
mat2 = np.array([[5,6],[7,8]])
mat3 = np.dot(mat1, mat2)
print(mat3)

[[19 22]
 [43 50]]
